# Generated by Django 3.0.5 on 2020-04-26 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupchat', '0002_auto_20200426_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
