# Generated by Django 3.0.5 on 2020-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0006_auto_20200426_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
